apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app-green
  labels:
    app: django-messaging
    version: green
    release: v2.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-messaging
      version: green
  template:
    metadata:
      labels:
        app: django-messaging
        version: green
        release: v2.0
    spec:
      containers:
      - name: django-app
        image: django-messaging:v2.0
        imagePullPolicy: Never  # Use local image for Minikube
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DEBUG
          value: "False"  # Production setting for green deployment
        - name: DJANGO_SETTINGS_MODULE
          value: "messaging_app.settings"
        - name: VERSION
          value: "2.0"
        - name: DEPLOYMENT_TYPE
          value: "green"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config-green
  labels:
    app: django-messaging
    version: green
data:
  ALLOWED_HOSTS: "*"
  CORS_ORIGIN_WHITELIST: "*"
  SECRET_KEY: "green-deployment-secret-key-change-in-production"
  VERSION: "2.0"
