pipeline {
    agent {
        docker {
            image 'python:3.9-slim'  // Use official Python image
            args '--user root'  // Run as root to avoid permission issues
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: 'main']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/JacobNjenga2/alx-backend-python.git',
                        credentialsId: 'f4abe732-4a19-4e1d-8d01-61bb2ee2bb15'
                    ]]
                ])
            }
        }
        
        stage('Setup Environment') {
            steps {
                dir('messaging_app') {
                    sh 'python -m venv venv'
                    sh 'source venv/bin/activate && python --version'
                }
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'source venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh 'source venv/bin/activate && python -m pytest --junitxml=test-results.xml'
                }
            }
            post {
                always {
                    junit 'messaging_app/test-results.xml'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed'
        }
    }
}