apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: django-messaging
    version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-messaging
  template:
    metadata:
      labels:
        app: django-messaging
        version: v1.0
    spec:
      containers:
      - name: django-app
        image: django-messaging:latest
        imagePullPolicy: Never  # Use local image for Minikube
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DEBUG
          value: "True"
        - name: MYSQL_DB
          value: "messaging_db"
        - name: MYSQL_USER
          value: "messaging_user"
        - name: MYSQL_PASSWORD
          value: "messaging_password"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: DJANGO_SETTINGS_MODULE
          value: "messaging_app.settings"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-config
          mountPath: /app/config
      volumes:
      - name: app-config
        configMap:
          name: django-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  ALLOWED_HOSTS: "*"
  CORS_ORIGIN_WHITELIST: "*"
  SECRET_KEY: "your-secret-key-here-change-in-production"
